version: '3.2'
services:
  api:
    container_name:  "main_api"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/usr/src/app
    ports:
      - "3000:3000"

networks:
  default:
    driver: bridge