version: '3.2'
services:
  msportal:
    # hostname: msportal
    container_name:  "adonisjs_msportal"
    build:
      context: .
      dockerfile: DockerfileDev
    command: sh ./docker-start-dev.sh
    environment:
      - NODE_ENV=dev
    volumes:
      - .:/home/app
      - /home/app/node_modules
    ports:
      - "3333:3333"
    networks:
      - default
  redis:
    container_name:  "redis_msportal"
    image: "redis:alpine"
    ports:
      - "6379:6379"
    networks:
      - default

#define network
networks:
  default:
    external:
      name: mspaytimepayment_default